Document: node
Title: Debian node Manual
Author: <insert document author here>
Abstract: This manual describes what node is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/node/node.sgml.gz

Format: postscript
Files: /usr/share/doc/node/node.ps.gz

Format: text
Files: /usr/share/doc/node/node.text.gz

Format: HTML
Index: /usr/share/doc/node/html/index.html
Files: /usr/share/doc/node/html/*.html
